[package]
name = "env2"
version = "0.3.1"
edition = "2021"
license = "MIT"
description = "A simple dotenv file parser for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
